"""empty message

Revision ID: 1a5b16540c55
Revises: 88eeeff4c097
Create Date: 2023-04-28 23:22:01.908966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5b16540c55'
down_revision = '88eeeff4c097'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
