version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: bancolegal
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbmysql:/var/lib/mysql

volumes:
  db_data: